global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: /metrics
    scrape_interval: 30s

  # ASA Control API metrics
  - job_name: 'ark-api'
    static_configs:
      - targets: ['ark-api:3000']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s

  # Node Exporter (optional - for host metrics)
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']

  # Docker daemon metrics (optional)
  # - job_name: 'docker'
  #   static_configs:
  #     - targets: ['docker:9323']
  #   metrics_path: /metrics 
